version: "3.8"

services:
  msp-2bit:
    container_name: PLCcapute-msp-2bit
    image: msp-2bit:latest
    restart: no
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  msp-16bit:
    container_name: PLCcapute-msp-16bit
    image: msp-16bit:latest
    restart: unless-stopped
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
  msp-32bit:
    container_name: PLCcapute-msp-32bit
    image: msp-32bit:latest
    restart: unless-stopped
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
